### ISSUE TITLE
Request a file ：'data/Agriculture-Vision-2021/sample_class_stats.json'

### ISSUE THREAD

**Issue by Akivilio** [edornd/agrivision-2022#1]
I'd like to request a file please, thanks.
'data/Agriculture-Vision-2021/sample_class_stats.json'

**Comment by edornd** [comment]
Hi, these files are just pixel stats that you can compute directly from the data itself. Nevertheless, I pushed my copy on the main branch, you can find them in `data` : https://github.com/edornd/agrivision-2022/commit/5d3a72a4310de94df81ad753f2a2f1691a96f1dc
