### ISSUE TITLE
What is the "gt" in the dataset?

### ISSUE THREAD

**Issue by Akivilio** [edornd/agrivision-2022#3]
Dear author:
The structure of agriculture-vision-2021 is different from that mentioned in the code, which makes it impossible to run the code. What is the "gt" in the dataset?   I can't find the gt folder, how do I get it
![image](https://github.com/edornd/agrivision-2022/assets/52814222/eee84a65-8116-4eb8-8a42-eb080cd92305)

What is the relationship between the dataset structure of the project and the original dataset? 
Thank you very much!

**Comment by edornd** [comment]
Check the README, there is a preprocessing script to generate multi-class semantic labels from this multi-label subdivision of the dataset, located in tools/convert_datasets/agrivision.py

**Comment by Akivilio** [comment]
Thank you so much. It was my carelessness that caused the problem. Thanks again.
